name: Basic Setup
description: Install tools and dependencies

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # 6.0.8
    - run: pnpm i --frozen-lockfile
      shell: bash
