root: true
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - '@typescript-eslint'
  - only-warn
  - eslint-plugin-import
extends:
  - eslint:recommended

env:
  browser: true
  node: true

rules:
  no-unused-vars:
    - 'off'
    - argsIgnorePattern: _.*
      varsIgnorePattern: _.*
  generator-star-spacing:
    - 'off'
  import/no-unused-modules:
    - 'warn'
    - unusedExports: true
  no-console: 'warn'

overrides:
  - files: ['*.js']
    excludedFiles: ['dist/*']
  - files: ['*.ts']
    excludedFiles: ['*.d.ts']
    extends:
      - plugin:@typescript-eslint/recommended
    rules:
      '@typescript-eslint/no-unused-vars':
        - 'warn'
        - argsIgnorePattern: _.*
          varsIgnorePattern: _.*
      '@typescript-eslint/explicit-module-boundary-types': 'off'
  - files: ['vite.build.ts', 'scripts/**/*', 'vite/**/*']
    rules:
      '@typescript-eslint/triple-slash-reference': 'off'
      '@typescript-eslint/no-non-null-assertion': 'off'
      '@typescript-eslint/no-explicit-any': 'off'
  - files: ['*.d.ts']
    rules:
      no-undef: 'off'
  - files: ['*.vue', '*.tsx', '*.jsx']
    extends:
      - plugin:vue/vue3-strongly-recommended
    rules:
      no-undef: 'off'
      vue/singleline-html-element-content-newline: 'off'
      vue/script-setup-uses-vars: 'warn'
      vue/html-closing-bracket-newline: 'off'
      vue/html-indent: 'off'
      vue/html-self-closing: 'off'
      vue/max-attributes-per-line: 'off'
      '@typescript-eslint/no-unused-vars': 'off'
  - files: ['scripts/**']
    rules:
      no-console: 'off'
