root: true
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - '@typescript-eslint'
  - only-warn
extends:
  - eslint:recommended

env:
  browser: true
  node: true

rules:
  no-unused-vars:
    - 'off'
    - argsIgnorePattern: _.*
      varsIgnorePattern: _.*
  generator-star-spacing:
    - 'off'

overrides:
  - files: ['*.js']
    excludedFiles: ['dist/*']
  - files: ['*.ts']
    excludedFiles: ['*.d.ts']
    extends:
      - plugin:@typescript-eslint/recommended
    rules:
      '@typescript-eslint/no-unused-vars':
        - 'warn'
        - argsIgnorePattern: _.*
          varsIgnorePattern: _.*
      '@typescript-eslint/ban-ts-comment': 'off'
      '@typescript-eslint/explicit-module-boundary-types': 'off'
  - files: ['*.d.ts']
    rules:
      no-undef: 'off'
  - files: ['*.vue', '*.tsx', '*.jsx']
    extends:
      - plugin:vue/vue3-strongly-recommended
      - '@vue/typescript/recommended'
      - '@vue/prettier'
      - '@vue/prettier/@typescript-eslint'
    rules:
      no-undef: 'off'
      vue/singleline-html-element-content-newline: 'off'
      vue/max-attributes-per-line: 'off'
      '@typescript-eslint/no-unused-vars':
        - 'warn'
        - argsIgnorePattern: _.*
          varsIgnorePattern: _.*
