services:
  backend:
    image: anime-skip/backend/api:dev
    ports:
      - 8081:8081
    env_file: .env
  db:
    image: postgres:alpine
    command: -p 9000
    ports:
      - 9000:9000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anime_skip_local
  db_ui:
    image: sosedoff/pgweb
    depends_on:
      - db
    ports:
      - 9001:8081
    links:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:9000/anime_skip_local?sslmode=disable
