name: Poll 9anime Domain
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  redirect:
    name: 9anime.to Redirect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        name: Install PNPM
        with:
          version: 7.x.x

      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Redirect
        run: pnpm esno scripts/check-9anime-domain.ts
