name: Verify PR
on:
  push:
    branches-ignore:
      - main
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch everything so we can filter since a revision

      - uses: pnpm/action-setup@v2.0.1
        name: Install PNPM
        with:
          version: 7.0.0

      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          CI: true

      - name: Validate Packages
        run: pnpm recursive run validate --filter [origin/main]
        env:
          CI: true
          PACKAGE_MODE: prod
          FIREFOX_SIGNING_ISSUER: ${{ secrets.FIREFOX_SIGNING_ISSUER }}
          FIREFOX_SIGNING_SECRET: ${{ secrets.FIREFOX_SIGNING_SECRET }}
          FIREFOX_SIGNING_ID: ${{ secrets.FIREFOX_SIGNING_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          CHROME_APP_ID: ${{ secrets.CHROME_APP_ID }}
