name: Verify PR
on:
  push:
    branches-ignore:
      - main
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@anime-skip'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch everything so we can filter since a revision

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.ANIME_SKIP_PACKAGES_TOKEN }}

      - name: Echo
        run: |
          echo "GITHUB_SHA $GITHUB_SHA"
          echo "GITHUB_REF $GITHUB_REF"
          echo "GITHUB_REF_NAME $GITHUB_REF_NAME"
          echo "GITHUB_REF_PROTECTED $GITHUB_REF_PROTECTED"
          echo "GITHUB_HEAD_REF $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF $GITHUB_BASE_REF"

      - name: Validate Packages
        run: pnpm recursive run validate --filter [origin/main]
        env:
          CI: true
          PACKAGE_MODE: prod
          NODE_AUTH_TOKEN: ${{ secrets.ANIME_SKIP_PACKAGES_TOKEN }}
          FIREFOX_SIGNING_ISSUER: ${{ secrets.FIREFOX_SIGNING_ISSUER }}
          FIREFOX_SIGNING_SECRET: ${{ secrets.FIREFOX_SIGNING_SECRET }}
          FIREFOX_SIGNING_ID: ${{ secrets.FIREFOX_SIGNING_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          CHROME_APP_ID: ${{ secrets.CHROME_APP_ID }}
